# FOR ORACLE DATABASE ...

#spring:
#    datasource:
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#        url: jdbc:oracle:thin:@localhost:1521:xe
#        username: system
#        password: system
#        hikari:
#            maximum-pool-size: 100000
#            minimum-idle: 2000
#            keepalive-time: 10000000
#    jpa:
#        database-platform: org.hibernate.dialect.OracleDialect
#        show-sql: true
#        hibernate:
#            ddl-auto: update
---
# For INSERTING DATA TO THE CUSTOMER

org:
    cust:
        customer-name: NTR
        customer-address: DEVARA
        customer-bill: 877.77
        gst: 65432.88
---

# For MYSQL DATABASE
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///data_jpa
        username: root
        password: root
        hikari:
            maximum-pool-size: 100000
            minimum-idle: 2000
            keepalive-time: 10000000
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        hibernate:
            ddl-auto: update